// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import '../ui/global.css';

// export default function RootLayout({ children }) {
//   return (
//     <html>
//       <body>{children}</body>
//     </html>
//   );
// }


export default function RootLayout({ children }) {
  return (
    <html>
      <body>
      <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
      <div className="w-full flex-none md:w-20">
        <SideNav />
        
      </div>
      <div className="flex-grow p-6 md:overflow-y-auto md:p-10">{children}</div>
     
    </div>
      <nav>
            <ul>
              <li>Home</li>
              <li>About</li>
              <li>Contact</li>
            </ul>
          </nav>
        <footer>

      {'Copyright © '}
      {/* <MuiLink color="inherit" href="https://palkar.one"> */}
        Palkar.one {' '}
      {/* </MuiLink>{' '} */}
      {new Date().getFullYear()}
      {'.'}
        </footer>
        {children}
      </body>
    </html>
  );
}